### ISSUE TITLE
Convert current layout to bootstrap

### ISSUE THREAD

**Issue by fimdomeio** [prgagarina167/bitnost-templates#2]

**Comment by prgagarina167** [comment]
Some comments, perhaps I need your opinion for those changes. 

1. Currently on 13" laptop (1280px width) I see 3 columns and a name of the section (Releases) on the left, almost as a separate column. I would prefer having 4 releases per row for this resolution/width. It's ok for me if the height of each row-block will be less dense (if it's necessary). 

2. Question about top margin as well. Basically, when navigation/filter will be added – you'll have to scroll (same laptop) to see the first release-row. I would strongly prefer having at least first row of releases visible immediately, so the header+menu has to be more condensed with smaller width.

Starting page has to sell records (I hope so very much), so the idea might be to show more news/information right away.

Let me know if you have questions/comments!
